import type { Metadata } from 'next'
import { Oswald } from 'next/font/google'
import { Theme } from '@radix-ui/themes'
import { HandleHeroesContextProvider } from '@/context/HandleHeroesContext'

import '@radix-ui/themes/styles.css'
import './globals.css'

const oswald = Oswald({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={oswald.className}>
        <HandleHeroesContextProvider>
          <Theme>{children}</Theme>
        </HandleHeroesContextProvider>
      </body>
    </html>
  )
}
